services:
  backend:
    build: ./backend
    ports:
      - "4500:4500"
    environment:
      MONGO_URI: mongodb://mongo:27017/tradehall
    depends_on:
      - mongo
    volumes:
      - ./backend:/app

  mongo:
    image: mongo
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
